name: Export

on:
  push:
    branches:
      - main

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: test-project
  PROJECT_PATH: test-project

jobs:
  client-win64:
    name: Windows Client Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Build
        run: |
          mkdir -v -p build/windows
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Client" "$EXPORT_DIR/windows/$EXPORT_NAME-client.exe"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-win64
          path: build/windows

  server-win64:
    name: Windows Server Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Build
        run: |
          mkdir -v -p build/windows
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Server" "$EXPORT_DIR/windows/$EXPORT_NAME-server.exe"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-win64
          path: build/windows
