name: Build Godot Project

on:
  push:
    branches:
      - main

env:
  GODOT_VERSION: 4.2.2
  EXPORT_NAME: test-project
  PROJECT_PATH: godot-test-project
  
jobs:
  export-windows-client:
    name: Windows Client Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mkdir -v -p ~/.config/godot
          ln -sv ~/.local/share/godot/templates ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
          cp -v /root/.config/godot/editor_settings-4.tres ~/.config/godot/editor_settings-4.tres
      - name: Windows Debug Build
        run: |
          mkdir -v -p build/windows
          cd client
          godot -v --headless --export-debug "Windows Desktop Client" ../build/windows/$EXPORT_NAME-client.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows-client
          path: build/windows
  export-windows-server:
    name: Windows Server Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mkdir -v -p ~/.config/godot
          ln -sv ~/.local/share/godot/templates ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
          cp -v /root/.config/godot/editor_settings-4.tres ~/.config/godot/editor_settings-4.tres
      - name: Windows Debug Build
        run: |
          mkdir -v -p build/windows
          cd server
          godot -v --headless --export-debug "Windows Desktop Server" ../build/windows/$EXPORT_NAME-server.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows-server
          path: build/windows
