name: Build Godot Project

on:
  push: {}
  pull_request: {}

env:
  GODOT_VERSION: 4.0.2
  EXPORT_NAME: test-project
  PROJECT_PATH: test-project
  
jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: srynetix/godot-ci:4.0.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: recursive
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mkdir -v -p ~/.config/godot
          ln -sv ~/.local/share/godot/templates ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
          cp -v /root/.config/godot/editor_settings-4.tres ~/.config/godot/editor_settings-4.tres
      - name: Windows Debug Build
        run: |
          mkdir -v -p build/windows
          cd $PROJECT_PATH
          godot -v --headless --export-debug "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: build/windows
