name: Export

on:
  push:
    branches:
      - main

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: test-project
  PROJECT_PATH: godot-test-project
  
jobs:
  client-win:
    name: Windows Client Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mkdir -v -p ~/.config/godot
          ln -sv ~/.local/share/godot/templates ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
          cp -v /root/.config/godot/editor_settings-4.tres ~/.config/godot/editor_settings-4.tres
      - name: Windows Debug Build
        run: |
          mkdir -v -p build/windows
          cd test-project
          godot -v --headless --export-debug "Windows Desktop Client" ../build/windows/$EXPORT_NAME-client.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: client-win
          path: build/windows
  server-win:
    name: Windows Server Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mkdir -v -p ~/.config/godot
          ln -sv ~/.local/share/godot/templates ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
          cp -v /root/.config/godot/editor_settings-4.tres ~/.config/godot/editor_settings-4.tres
      - name: Windows Debug Build
        run: |
          mkdir -v -p build/windows
          cd test-project
          godot -v --headless --export-debug "Windows Desktop Server" ../build/windows/$EXPORT_NAME-server.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: server-win
          path: build/windows
